[package]
name = "uwu"
version = "0.1.0"
authors = ["Ramsey Shaban <44956449+rshaban@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
